/* ============================================================
   HINTS - one proven winning plan per level

   GENERATED by tools/genhints.mjs. Do not edit by hand: every
   entry was found by running the real simulator on the level's
   own seed (levels/index levelSeed), so it is known to win.
   A level with no entry here simply has no hint button.

     node tools/genhints.mjs            # every level
     node tools/genhints.mjs 41-60      # just those, merged in
   ============================================================ */
import type { Hint } from './types';

export const HINTS: Record<number, Hint> = {
  1: { ramps: [{ x1: 61, y1: 89, x2: 163, y2: 151 }] },
  2: { ramps: [{ x1: 404, y1: 60, x2: 408, y2: 180 }] },
  3: { ramps: [{ x1: 117, y1: 65, x2: 163, y2: 175 }] },
  17: { ramps: [{ x1: 13, y1: 561, x2: 105, y2: 639, spring: true }], t0: 10 },
};
